### ISSUE TITLE
Upgrade to webpack 5 after webpack-dev-server 4 has been released

### ISSUE THREAD

**Issue by keskiju** [TaitoUnited/full-stack-template#113]
Migration from webpack 4 to webpack 5: https://webpack.js.org/migrate/5/

https://github.com/webpack/webpack-dev-server/releases
--> [webpack-dev-server 4 beta](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0) has already been released. We can do migration based on that on a feature branch and update later.

See also #21 and #112.

**Comment by Flibo** [comment]
FYI, webpack-dev-server 3 works with webpack 5.

In my experience, webpack-dev-server 4 doesn't play nice, so it's probably smart to stay on 3 for now.

https://github.com/webpack/webpack-dev-server/blob/master/CHANGELOG.md#bug-fixes-4
