### ISSUE TITLE
Uniform client and server conventions

### ISSUE THREAD

**Issue by keskiju** [TaitoUnited/full-stack-template#60]
Use uniform conventions for client and server:

* [ ] Babel vs no Babel. Babel required for webpack but plain tsc better for backend? Jest works ok without babel on backend?
* [x] TSLint is deprecated and therefore should not be used (currently in use on server)
* [x] Uniform linting and prettier rules (e.g. single quotes vs. double quotes)

**Comment by AntiPaste** [comment]
TSLint replaced with eslint. #81
